# This workflow deploys the site to the live channel on Firebase Hosting
# when a commit is pushed to the 'main' branch.

name: Deploy to Firebase Hosting on Merge
'on':
  push:
    branches:
      - main # Important: Change this if your main branch is named something else (e.g., 'master')

permissions:
  checks: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SARCA_ARDENTE }}'
          projectId: sarca-ardente
          channelId: live # This is the crucial line that targets the live channel